### ISSUE TITLE
One of the problems I encountered

### ISSUE THREAD

**Issue by g-cool-wind** [THU-BPM/chatgpt-sql#5]
I'm sorry to bother you, but I'm having a problem trying to reproduce your code. generate_txt.py only creates gold_example.txt and pred_example.txt, but not tables.json, and there is no such file in your directory. I would like to ask how this tables.json file is created?

**Comment by exlaw** [comment]
For spider and its related datasets, download the file from the spider's official website https://yale-lily.github.io//spider, and for other datasets, download links are also available on their official website.

**Comment by g-cool-wind** [comment]
Thank you for your reply, I would like to confirm, do all datasets have to be downloaded again from the official website? 
In your GitHub project, there is no tables.json file under each dataset folder. 
If I want to run the code on other datasets, do I just need to change '--db' parameter  and '--table'parameter. 
Or do I need to regenerate gold_example.txt and pred_example.txt. 
Does the --etype parameter need to be modified.
I would appreciate if you could take the time to get back to me.

**Comment by exlaw** [comment]
yes, this repo only provides the generation result of chatgpt.  The --etyp does not required to be modified unless you would like to test the exact match accuracy.

**Comment by davies-w** [comment]
Hi, sorry, it's really not clear what this repo does? It looks to me like you have "saved" the chatGPT responses, and are running the generated SQL against the database, is that correct?

**Comment by davies-w** [comment]
Where did you generate the data for the other approaches in the paper, or did you copy their results into your paper (fine approach, its just not clear). 

What exactly does this repo actually do?

**Comment by davies-w** [comment]
Hmm. 

python evaluation.py --gold gold_example.txt  --pred pred_example.txt --etype exec --db spider/database --table spider/tables.json
                     easy                 medium               hard                 extra                all
count                0                    0                    0                    0                    0
=====================   EXECUTION ACCURACY     =====================
execution            0.000                0.000                0.000                0.000                0.000

**Comment by davies-w** [comment]
Ok, you should probably update your README - 

add the location of tables.json (described above, but not simple to find, as its embedded in the Spider zip https://drive.google.com/uc?export=download&id=1TqleXec_OykOYFREKKtschzY29dUcVAQ)

pip install nltk # that's obvious as it throws an error
import nltk
nltk.download('punkt')

**Comment by exlaw** [comment]
I've updated the readme to incorporate the links for all the datasets. This repository houses the generation results from ChatGPT for all text-to-SQL datasets.

As for alternative methodologies, I obtain results directly from the associated papers whenever available. In the absence of published results, I conduct the tests independently and provide the findings.

**Comment by Zhongyan0721** [comment]
Does someone have the dataset of ADVETA? I couldn't find it in the link. Or should I just use the dataset of spider to evaluate the result generated from ADVETA?
