### ISSUE TITLE
Question about database

### ISSUE THREAD

**Issue by Zhongyan0721** [THU-BPM/chatgpt-sql#7]
Does someone know how to evaluate ADVETA? I am confusing since there seems no database of it and the program requires a database to evaluate. Or should I just use the spider database?

**Comment by Zhongyan0721** [comment]
Also, where is the tables.json of Dusql? Could someone help me?

**Comment by exlaw** [comment]
> Does someone know how to evaluate ADVETA? I am confusing since there seems no database of it and the program requires a database to evaluate. Or should I just use the spider database?

For ADVETA,  you could download the table replacement or 
 addition candidates from https://github.com/microsoft/ContextualSP/blob/master/robustness_of_text_to_sql/adveta_1.0.zip, then change the database and tables.json file of the origin SPIDER dataset.

**Comment by Zhongyan0721** [comment]
Thank you for the reply!
Sorry to brother you again, but I encountered another problem: what does db2 in evaluate.py serve for?

**Comment by exlaw** [comment]
When using EX to evaluate the ADVETA dataset,  the database of the generated SQL and the origin SQL is different (names are replaced or added), we need to use two databases in the process.

**Comment by Zhongyan0721** [comment]
Got it! So, what about the tables.json? Do we need to use the modified version?

**Comment by exlaw** [comment]
This is not required because tables.json is not needed to parse the SQL during EX detection.

**Comment by Zhongyan0721** [comment]
Could you provide the database and tables.json for ADVETA and DuSQL? I will be very grateful if you can provide these files.

**Comment by Zhongyan0721** [comment]
solved

**Comment by LeiShenVictoria** [comment]
> solved

Hi, how to obtain "database" of DuSQL?

**Comment by Zhongyan0721** [comment]
I obtained it by extracting db information from the schema and then creating corresponding sqlite files.
