### ISSUE TITLE
EX Evaluation on Chinese Text2SQL datasets.

### ISSUE THREAD

**Issue by Aolius** [THU-BPM/chatgpt-sql#9]
Hi, thank you for sharing your work with us!
I am curious about the EX evaluation process for CSpider and DuSQL. Could you help me on the following questions?
1. In CSpider, the annotations of table values remain in English, causing a mismatch of the Chinese questions/SQLs with the databases. So it looks impossible to get the correct execution results on examples like this:
<img width="623" alt="image" src="https://github.com/THU-BPM/chatgpt-sql/assets/13333597/815f832d-1790-4082-9048-52674629c987">

Could you let me know how you address this problem to realize the EX evaluation?

2. In DuSQL, the downloading link seems expired, and I cannot find the .sqlite database files from the other links online. Could you provide the database files?

**Comment by exlaw** [comment]
1.  This is indeed an issue. We have not expanded the database, so it may judge these data as correct just because the query results are empty. We could expand the values in the database for more precise detection.
2.  Refer to this link https://cloud.tsinghua.edu.cn/f/c137e7fb19094637a5df/

**Comment by Aolius** [comment]
Thanks a lot!
